# Generated by Django 6.0.5 on 2026-06-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_nome', models.CharField(max_length=100, verbose_name='Nome do Servidor/Usuário')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor/Departamento')),
                ('categoria', models.CharField(choices=[('computador', 'Computador / Hardware'), ('software', 'Instalação / Erro de Software'), ('rede', 'Internet / Rede'), ('email', 'E-mail Institucional'), ('impressora', 'Impressora / Scanner'), ('acesso', 'Sistemas / Senhas / Acessos'), ('outros', 'Outros Assuntos')], default='computador', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa (Não impede o trabalho)'), ('media', 'Média (Dificulta o trabalho)'), ('alta', 'Alta (Impede o trabalho)')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto / Aguardando Atendimento'), ('atendimento', 'Em Atendimento'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='aberto', max_length=15)),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('observacao_tecnica', models.TextField(blank=True, null=True, verbose_name='Observações da Resolução')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
